CREATE OR REPLACE WAREHOUSE SUPPLY_CHAIN_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE SUPPLY_CHAIN_WH;


CREATE OR REPLACE DATABASE SUPPLY_CHAIN_DB;
USE DATABASE SUPPLY_CHAIN_DB;


CREATE OR REPLACE SCHEMA SCM;
USE SCHEMA SCM;

SELECT
    CURRENT_WAREHOUSE() AS Warehouse_Name,
    CURRENT_DATABASE() AS Database_Name,
    CURRENT_SCHEMA() AS Schema_Name;